#!/bin/bash

Lsb_release() {
    local file=/etc/lsb-release

    sed -i $file \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=SteavenLinux|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"SteavenLinux\"|'
}

Os_release() {
    local file=/etc/os-release

    sed -i $file \
        -e 's|^NAME=.*$|NAME=\"SteavenLinux\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"SteavenLinux\"|' \
        -e 's|^ID=.*$|ID=SteavenLinux|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
        -e 's|^ANSI_COLOR=.*$|ANSI_COLOR=\"38;2;23;147;209\"|' \
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://github.com/SteavenLinux/\"|' \
        -e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL=\"https://github.com/SteavenLinux/\"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://discord.gg/G8cSyTj6er/\"|' \
        -e 's|^BUG_REPORT_URL=.*$|BUG_REPORT_URL=\"https://github.com/SteavenLinux\"|' \
        -e 's|^LOGO=.*$|LOGO=steavenlinux|'

    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi
}

Issues() {
    sed -i 's|Arch Linux|SteavenLinux|g' /etc/issue /usr/share/factory/etc/issue
}

Main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        "")          Os_release
                     Lsb_release
                     Issues
                     ;;
    esac
}

Main "$@"