#!/bin/bash

# Set the default configuration path
DEFAULT_CONFIG="/opt/hyfetch/config.conf"

# Check if any arguments are provided
if [[ "$#" -gt 0 ]]; then
    # Run neofetch with the provided arguments without the default config
    /usr/bin/neowofetch "$@"
else
    # Run neofetch with the default configuration
        /usr/bin/neowofetch --config "$DEFAULT_CONFIG" | lolcat
fi